image: ruby:2.3

stages:
  - mirror
  - lint
  - build

mirror:
  image: alpine:latest
  stage: mirror
  variables:
    GIT_STRATEGY: clone
  only:
    - master
  script:
    - apk add --update git
    - git remote set-url --push origin https://$GITHUB_ACCESS_TOKEN@github.com/brgmnn/abstract_image.git
    - git checkout master
    - git push origin master --force

lint:
  stage: lint
  script:
    - gem install rubocop --version 0.41.1
    - rubocop

build:
  stage: build
  script:
    - bundle install --deployment
    - gem build abstract_image.gemspec
